apiVersion: v1
kind: ReplicationController
metadata:
  name: myap-rc
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 2
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-contaroller
          image: nginx
