apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: random-error
spec:
  completions: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: anoop600/random_error:1
        name: random-error
      restartPolicy: Never
status: {}
