apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
  labels:
    author: anoop
    app: add
spec:
  completions: 3
  template:
    metadata:
      labels:
        app: add
        author: anoop
    spec:
      restartPolicy: Never
      containers:
      - image: busybox
        name: math-add-job
        command: ['expr', '5', '+', '2']
