apiVersion: batch/v1
kind: Job
metadata:
  name: random-error
  labels:
    app: random-error
spec:
  completions: 3
  parallelism: 3
  template:
    metadata:
      labels:
        app: random-error
    spec:
      containers:
      - image: anoop600/random_error:1
        name: random-error
      restartPolicy: Never
