apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-service
    app: demo-voting-app
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
