apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-pod
        app: demo-voting-app
      name: redis-pod
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
          - containerPort: 6379
