apiVersion: v1
kind: Service
metadata:
  labels:
    name: result-app-service
    app: demo-voting-app
  name: result-service
spec:
  type: NodePort
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: result-pod
    app: demo-voting-app
