apiVersion: v1
kind: Pod
metadata:
  labels:
    name: postgres-pod
    app: demo-voting-app
  name: postgres-pod
spec:
  containers:
  - env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: password
    image: postgres
    name: postgres
    ports:
    - containerPort: 5432
