apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-service
    app: demo-voting-app
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
