apiVersion: v1
kind: Pod
metadata:
  labels:
    name: result-pod
    app: demo-voting-app
  name: result-pod
spec:
  containers:
  - image: kodekloud/examplevotingapp_result:v1
    name: result-pod
    ports:
      - containerPort: 80
