apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: node
  labels:
    app: nodejs-demo
    name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-demo
      name: nodejs-pod
  template:
    metadata:
      name: nodejs-pod
      labels:
        name: nodejs-pod
        app: nodejs-demo
    spec:
      containers:
        - name: nodejs
          image: anoop600/example_nodejs:main
          env:
            - name: BG_COLOR
              value: "red"
            - name: PORT
              value: "3000"
