apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-demo
    name: nodejs-deployment
  name: nodejs-nodeport-svc
  namespace: node
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs-demo
    name: nodejs-pod
  type: NodePort
