apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: anoop600/example_nodejs:main
        name: example-nodejs
        ports:
          - name: app-port
            containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: BG_COLOR
          value: orange
        startupProbe:
          failureThreshold: 10 
          periodSeconds: 10
          httpGet:
            path: /health/readiness?delay=20
            port: app-port
        readinessProbe:
          initialDelaySeconds: 20
          successThreshold: 3
          httpGet:
            path: /health/readiness?delay=20
            port: app-port
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /health/liveness
            port: app-port
